import ThetaTrial.Paper.LogUncertainty
import ThetaTrial.Paper.Definitions
import ThetaTrial.Paper.FullForm
import ThetaTrial.Paper.BV
import ThetaTrial.Paper.Archimedean
import ThetaTrial.Paper.FormDomain
import ThetaTrial.Paper.TailVariation
import ThetaTrial.Paper.TailFormBound
import ThetaTrial.Paper.Laguerre
import ThetaTrial.Paper.PolynomialCoefficientBounds
import ThetaTrial.Paper.ThetaFourier
import ThetaTrial.Paper.ThetaNormalization
import ThetaTrial.Paper.ThetaStrip
import ThetaTrial.Paper.ThetaStripDecay
import ThetaTrial.Paper.ThetaKernel
import ThetaTrial.Paper.Multiplier
import ThetaTrial.Paper.ThetaModes
import ThetaTrial.Paper.Contour
import ThetaTrial.Paper.ContourDeformation
import ThetaTrial.Paper.ContourArcIdentity
import ThetaTrial.Paper.ShiftedAverageBound
import ThetaTrial.Paper.ContourModeEstimate
import ThetaTrial.Paper.ShiftedAverageAnalytic
import ThetaTrial.Paper.ThetaAvgContour
import ThetaTrial.Paper.Radical
import ThetaTrial.Paper.RadicalApproximation
import ThetaTrial.Paper.ShiftedAverageFourier
import ThetaTrial.Paper.TrialFourier
import ThetaTrial.Paper.ThetaAvgTailEnvelope
import ThetaTrial.Paper.ThetaAvgTail
import ThetaTrial.Paper.RadicalCorrelation
import ThetaTrial.Paper.RadicalCutoff
import ThetaTrial.Paper.RadicalSource
import ThetaTrial.Paper.ThetaAvgPolynomialRegularity
import ThetaTrial.Paper.ThetaAvgPolynomialNorm
import ThetaTrial.Paper.WindowTrial
import ThetaTrial.Paper.BVWindowDomain
import ThetaTrial.Paper.ClosedFormRepresentation
import ThetaTrial.Paper.CoerciveFormRepresentation
import ThetaTrial.Paper.CompactFormSpectrum
import ThetaTrial.Paper.WeightedBVMeasure
import ThetaTrial.Paper.ThetaDerivativeSeries
import ThetaTrial.Paper.ThetaConcentration
import ThetaTrial.Paper.TrialFourierComplex
import ThetaTrial.Paper.ThetaDerivPolynomialRegularity
import ThetaTrial.Paper.ThetaDerivTailMoments
import ThetaTrial.Paper.ShiftParseval
import ThetaTrial.Paper.GammaCrossMagnitude
import ThetaTrial.Paper.GammaCross
import ThetaTrial.Paper.ThetaDerivPrimeSums
import ThetaTrial.Paper.ThetaDerivPrimeAssembly
import ThetaTrial.Paper.ThetaDerivPrimeFactor
import ThetaTrial.Paper.ThetaDerivPolePrimes
import ThetaTrial.Paper.ThetaDerivSourceLocalization
import ThetaTrial.Paper.WindowFormBounds
import ThetaTrial.Paper.ComplexPrimeSeries
import ThetaTrial.Paper.ShiftMeasure
import ThetaTrial.Paper.ComplexShiftMeasure
import ThetaTrial.Paper.RadicalSourceAlgebra
import ThetaTrial.Paper.RadicalConsequences
import ThetaTrial.Paper.ComplexShiftPolynomial
import ThetaTrial.Paper.ComplexShiftDecay
import ThetaTrial.Paper.EvenShiftWeights
import ThetaTrial.Paper.FormCore
import ThetaTrial.Paper.FormMinMax
import ThetaTrial.Paper.FullFormScaling
import ThetaTrial.Paper.FullPairingAlgebra
import ThetaTrial.Paper.InvariantFormReflection
import ThetaTrial.Paper.L2Reflection
import ThetaTrial.Paper.ThetaPolynomialRadical
import ThetaTrial.Paper.TailDerivativeMeasure
import ThetaTrial.Paper.MeasureRadicalBound
import ThetaTrial.Paper.ThetaDerivScalarAbsorption
import ThetaTrial.Paper.ThetaDerivSector
import ThetaTrial.Paper.ThetaAvgTrialDimension
import ThetaTrial.Paper.ThetaDerivTrialSpace
import ThetaTrial.Paper.ShiftWeightMass
import ThetaTrial.Paper.ShiftedAverageInterior
import ThetaTrial.Paper.TrialBounds
import ThetaTrial.Paper.ThetaAvgEnergy
import ThetaTrial.Paper.ThetaAvgRadical
import ThetaTrial.Paper.ThetaAvgNormalization
import ThetaTrial.Paper.ThetaAvgMain
import ThetaTrial.Paper.ThetaAvgPolynomialTail
import ThetaTrial.Paper.ThetaAvgScalarAbsorption
import ThetaTrial.Paper.ThetaAvgPolynomialTheorem
import ThetaTrial.Paper.ThetaAvgSpaces
import ThetaTrial.Paper.ThetaAvgSpaceVectors
import ThetaTrial.Paper.ParityFormEmbedding
import ThetaTrial.Paper.PhysicalGammaConstant
import ThetaTrial.Paper.Reflection
import ThetaTrial.Paper.ReflectionPairing
import ThetaTrial.Paper.RadicalBV
import ThetaTrial.Paper.PhysicalWeilIdentity
import ThetaTrial.Paper.SesquilinearBound
import ThetaTrial.Paper.ShiftDensity
import ThetaTrial.Paper.ShiftMassAsymptotic
import ThetaTrial.Paper.ThetaPolynomialDecay
import ThetaTrial.Paper.WindowFormAssembly
import ThetaTrial.Paper.WindowFormCore
import ThetaTrial.Paper.WindowInfiniteDimension
import ThetaTrial.Paper.WindowOperator
import ThetaTrial.Paper.WindowParity
import ThetaTrial.Paper.WindowOperatorParity
import ThetaTrial.Paper.WindowSpectrum
import ThetaTrial.Paper.WindowParitySpectrum
import ThetaTrial.Paper.WindowOperatorParityRestriction
import ThetaTrial.Paper.WindowParityCore
import ThetaTrial.Paper.WindowTrialSpectrum

/-! Lean formalization of "Explicit theta trial spaces for the truncated Weil
quadratic form". This file imports every module of the development;
`verification/coverage.json` lists the Lean theorem for each numbered result of
the paper. -/
